spring:
  application:
    name: ORDER
  datasource:
    url: jdbc:mysql://localhost:3306/udai?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.0.201
    port: 6379
    database: 0
    timeout: 1500
  rabbitmq:
    host: 192.168.0.210
    username: admin
    password: admin
    port: 5672
    virtual-host: /
    connection-timeout: 15000
    publisher-returns: true
    publisher-confirms: true    #消息发送到交换机确认机制
    template:
      mandatory: true   #消息找不到队列 不删除
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.oracle.udai.order.domain.dto
feign:
  hystrix:
    enabled: true   #开启feign远程调用的hystrix降级处理
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000   #降级时间允许10s
ribbon:
  ReadTimeout: 5000
  ConnectionTimeout: 5000  #ribbon连接超时必须小于hystrix
management:
  endpoints:
    web:
      exposure:
        include: "*"