spring:
  application:
    name: PAY
  datasource:
    url: jdbc:mysql://localhost:3306/udai?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 80
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.oracle.udai.api.domain.dto